apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifactory-pull
  namespace: team-a
  annotations:
    JFrogExchange: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifactory-pull
  namespace: team-b
  annotations:
    JFrogExchange: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifactory-pull
  namespace: team-c
  annotations:
    JFrogExchange: "true"
