{{- $cloudProvider := include "jfrog-credential-provider.cloudProvider" . }}
{{- if and .Values.rbac.create (or (eq $cloudProvider "aws") (eq $cloudProvider "azure") (eq $cloudProvider "gcp")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jfrog-credential-provider.fullname" . }}
  namespace: {{ include "jfrog-credential-provider.namespace" . }}
  labels:
    {{- include "jfrog-credential-provider.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jfrog-credential-provider.fullname" . }}
subjects:
  - kind: Group
    name: system:nodes
    apiGroup: rbac.authorization.k8s.io
{{- end }}

