{{- if and (not .Values.binaryDownload.auth.existingSecret)
           (or .Values.binaryDownload.auth.username .Values.binaryDownload.auth.accessToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jfrog-credential-provider.fullname" . }}-download-auth
  namespace: {{ include "jfrog-credential-provider.namespace" . }}
  labels:
    {{- include "jfrog-credential-provider.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.binaryDownload.auth.username }}
  username: {{ .Values.binaryDownload.auth.username | b64enc }}
  password: {{ .Values.binaryDownload.auth.password | b64enc }}
  {{- end }}
  {{- if .Values.binaryDownload.auth.accessToken }}
  accessToken: {{ .Values.binaryDownload.auth.accessToken | b64enc }}
  {{- end }}
{{- end }}
