providerConfig:
  - name: jfrog-credentials-provider
    artifactoryUrl: "<artifactory-url>"
    matchImages:
      - "*.<test.your-org.domain.io>"
    defaultCacheDuration: 5h
    tokenAttributes:
      enabled: true
    gcp:
      enabled: true
      google_service_account_email: "<google-service-account-email>"
      jfrog_oidc_audience: "artifactory"
      jfrog_oidc_provider_name: "<jfrog-oidc-provider-name>"

rbac:
  create: true

serviceAccount:
  create: true
  annotations:
    "iam.gke.io/gcp-service-account": "<google-service-account-email>"
    "JFrogExchange": "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: credentialsProviderEnabled
              operator: In
              values:
                - "true"
